version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always
  exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: always
