version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.17.2
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always
  exporter:
    image: prom/node-exporter:v0.18.1
    command: 
      - "--collector.textfile.directory=/tmp"
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      - ./volumes/collector:/tmp
  grafana:
    image: grafana/grafana:6.7.3
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana_dashboards
      - ./volumes/grafana:/var/lib/grafana
    user: "1000"
    ports:
      - 3000:3000
  collector:
    build: ./prom_metrics_collector
    volumes: 
      - ./volumes/collector:/tmp
