version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.17.2
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always
  exporter:
    image: prom/node-exporter:v0.18.1
    ports:
      - 9100:9100
    restart: always
  grafana:
    image: grafana/grafana:6.7.3
    ports:
      - 3000:3000
    restart: always
