global:
  scrape_interval:     1m 
  evaluation_interval: 1m 
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
#  - /etc/prometheus/alert.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - exporter:9100

