{
 "title": "Bug tracker",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "milestone", "label": "Milestone", "query": "label_values(milestone)" },
   { "name": "vl", "label": "VL", "query": "label_values(vl)" },
   { "name": "sp", "label": "SP", "query": "label_values(sp)" }
  ]
 },
 "panels": [
  {
   "title": "Total Issues(ALL)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(gitlab_bug{milestone=~\".*\", vl=~\".*\", sp=~\".*\"})"
    }
   ]
  },
  {
   "title": "Total Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(gitlab_bug{milestone=~\"$milestone\", vl=~\"$vl\", sp=~\"$sp\"})"
    }
   ]
  },
  {
   "title": "Open Issues(ALL)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(gitlab_bug{state=\"opened\", milestone=~\".*\", vl=~\".*\", sp=~\".*\"})"
    }
   ]
  },
  {
   "title": "Open Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(gitlab_bug{state=\"opened\", milestone=~\"$milestone\", vl=~\"$vl\", sp=~\"$sp\"})"
    }
   ]
  },
  {
   "title": "Closed Issues(ALL)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(gitlab_bug{state=\"closed\", milestone=~\".*\", vl=~\".*\", sp=~\".*\"})"
    }
   ]
  },
  {
   "title": "Closed Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum(gitlab_bug{state=\"closed\", milestone=~\"$milestone\", vl=~\"$vl\", sp=~\"$sp\"})"
    }
   ]
  },
  {
   "title": "Label1(Total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label1) (gitlab_bug_label1{milestone=~\"$milestone\", vl=~\"$vl\", sp=~\"$sp\"})",
     "legendFormat": "{{label1}}"
    }
   ]
  },
  {
   "title": "Label1(Opened)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label1) (gitlab_bug_label1{state=\"opened\", milestone=~\"$milestone\", vl=~\"$vl\", sp=~\"$sp\"})",
     "legendFormat": "{{label1}}"
    }
   ]
  },
  {
   "title": "Label1(closed)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label1) (gitlab_bug_label1{state=\"closed\", milestone=~\"$milestone\", vl=~\"$vl\", sp=~\"$sp\"})",
     "legendFormat": "{{label1}}"
    }
   ]
  },
  {
   "title": "Label2(Total)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label2) (gitlab_bug_label2{milestone=~\"$milestone\", vl=~\"$vl\", sp=~\"$sp\"})",
     "legendFormat": "{{label2}}"
    }
   ]
  },
  {
   "title": "Label2(Opened)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label2) (gitlab_bug_label2{state=\"opened\", milestone=~\"$milestone\", vl=~\"$vl\", sp=~\"$sp\"})",
     "legendFormat": "{{label2}}"
    }
   ]
  },
  {
   "title": "Label2(closed)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (label2) (gitlab_bug_label2{state=\"closed\", milestone=~\"$milestone\", vl=~\"$vl\", sp=~\"$sp\"})",
     "legendFormat": "{{label2}}"
    }
   ]
  }
 ]
}